spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <from github developer settings>
            client-secret: <from github developer settings>

