spring:
  data:
    mongodb:
      uri: mongodb+srv://mongouser:mongouser@mflix.lgx38.mongodb.net/?retryWrites=true&w=majority
      database: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: "abc@gmail.com"
    password: "xyz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  jpa:
    hibernate:
      ddl-auto: none

server:
  error:
    whitelabel:
      enabled: false
