spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: https://console.cloud.google.com/apis/credentials?project=learnoauth2-329111
            client-secret: https://console.cloud.google.com/apis/credentials?project=learnoauth2-329111
